/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibrary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wowya
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        this.setSize(1350,700);
        setIconImage(new ImageIcon(getClass().getResource("pic.jpg")).getImage());
        l5.setVisible(false);
                tf6.setVisible(false);
                tf5.setVisible(false);
                l6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta4 = new javax.swing.JTextArea();
        l5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        l6 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Name of the book:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 110, 110, 15);

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(560, 100, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Author:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 165, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Book Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 50, 60, 15);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(560, 40, 170, 30);
        getContentPane().add(tf3);
        tf3.setBounds(560, 160, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Description: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 220, 80, 15);

        ta4.setColumns(20);
        ta4.setRows(5);
        jScrollPane1.setViewportView(ta4);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 220, 320, 120);

        l5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l5.setForeground(new java.awt.Color(240, 240, 240));
        l5.setText("URL(if digital):");
        getContentPane().add(l5);
        l5.setBounds(480, 370, 80, 15);
        getContentPane().add(tf5);
        tf5.setBounds(610, 360, 270, 30);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        r1.setForeground(new java.awt.Color(240, 240, 240));
        r1.setText("Digital");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(360, 370, 70, 23);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        r2.setForeground(new java.awt.Color(240, 240, 240));
        r2.setText("Physical");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(360, 440, 80, 23);

        l6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l6.setForeground(new java.awt.Color(240, 240, 240));
        l6.setText("Rack/column:");
        getContentPane().add(l6);
        l6.setBounds(480, 440, 80, 15);
        getContentPane().add(tf6);
        tf6.setBounds(610, 430, 270, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 580, 110, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Category:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 500, 60, 15);
        getContentPane().add(tf7);
        tf7.setBounds(580, 490, 190, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibrary/black_light_dark_figures_73356_1920x1200.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 40, 1260, 660);

        jButton2.setText("Signout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1060, 10, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
     l5.setVisible(true);
     tf5.setVisible(true);
     l6.setVisible(false);
     tf6.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
l6.setVisible(true);
     tf6.setVisible(true);
     l5.setVisible(false);
     tf5.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(r1.isSelected()==true)
{
try{  
                                        Class.forName("oracle.jdbc.driver.OracleDriver");  
                                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","library","amit");   
                                        Statement stmt=con.createStatement();  
                                        
                                        String stat="insert into digitalbooks values('"+tf1.getText()+"','"+tf2.getText()+"','"+tf3.getText()+"','"+ta4.getText()+"','"+tf5.getText()+"','"+tf7.getText()+"','available')";
                                        
                                        stmt.executeUpdate(stat);  
                                        
                                        con.close();  
                                         JOptionPane.showMessageDialog(null, tf2.getText()+" was sucessfully added");
  
                                      }catch(Exception e){ System.out.println(e);} 
}
else if(r2.isSelected()==true)
{
try{  
                                        Class.forName("oracle.jdbc.driver.OracleDriver");  
                                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","library","amit");   
                                        Statement stmt=con.createStatement();  
                                        
                                        String stat="insert into physicalbooks values('"+tf1.getText()+"','"+tf2.getText()+"','"+tf3.getText()+"','"+ta4.getText()+"','"+tf6.getText()+"','"+tf7.getText()+"','available')";
                                        
                                        stmt.executeUpdate(stat);  
                                        
                                        con.close();  
                                         JOptionPane.showMessageDialog(null, tf2.getText()+" was sucessfully added");
  
                                      }catch(Exception e){ System.out.println(e);}
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
frame1 f1= new frame1();
f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBooks ab=new AddBooks();
                ab.setVisible(true);
                ab.l5.setVisible(false);
                ab.tf6.setVisible(false);
                ab.tf5.setVisible(false);
                ab.l6.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextArea ta4;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    // End of variables declaration//GEN-END:variables
}
