/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlibrary;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author wowya
 */
public class booksearch extends javax.swing.JFrame {

    /**
     * Creates new form booksearch
     */
    public booksearch() {
        initComponents();
        this.setSize(1350,700);
        setIconImage(new ImageIcon(getClass().getResource("pic.jpg")).getImage());
        b3.setVisible(false);
        b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        tf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ls = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Search");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 50, 50, 20);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Author", "Category" }));
        getContentPane().add(c2);
        c2.setBounds(370, 50, 80, 30);
        getContentPane().add(tf1);
        tf1.setBounds(520, 50, 160, 30);

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 50, 80, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Book", "Digital book" }));
        getContentPane().add(c1);
        c1.setBounds(160, 50, 120, 30);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("By");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 50, 20, 30);

        ls.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ls.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ls);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(75, 126, 373, 412);

        jButton1.setText("Open Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(517, 197, 124, 46);

        b3.setText("Open and Read");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(526, 287, 120, 40);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Book name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 190, 80, 20);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Author:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 230, 50, 20);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Description:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 290, 70, 20);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Book Id:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 150, 50, 20);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Availability");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 530, 60, 20);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Category:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(750, 480, 60, 20);

        l9.setForeground(new java.awt.Color(240, 240, 240));
        l9.setText(".");
        getContentPane().add(l9);
        l9.setBounds(860, 150, 310, 20);

        l10.setForeground(new java.awt.Color(240, 240, 240));
        l10.setText(".");
        getContentPane().add(l10);
        l10.setBounds(860, 190, 220, 20);

        l11.setForeground(new java.awt.Color(240, 240, 240));
        l11.setText(".");
        getContentPane().add(l11);
        l11.setBounds(860, 230, 210, 20);

        ta2.setColumns(20);
        ta2.setRows(5);
        jScrollPane1.setViewportView(ta2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(860, 290, 300, 110);

        l12.setForeground(new java.awt.Color(240, 240, 240));
        l12.setText(".");
        getContentPane().add(l12);
        l12.setBounds(850, 480, 250, 20);

        l13.setForeground(new java.awt.Color(240, 240, 240));
        l13.setText(".");
        getContentPane().add(l13);
        l13.setBounds(850, 530, 290, 20);

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Rack/location");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(750, 440, 80, 20);

        l14.setForeground(new java.awt.Color(240, 240, 240));
        l14.setText(".");
        getContentPane().add(l14);
        l14.setBounds(850, 440, 220, 20);

        b4.setText("Request book");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(526, 385, 120, 30);

        jButton3.setText("Sign Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(984, 21, 90, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectlibrary/black_light_dark_figures_73356_1920x1200.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1620, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String typ=(String)c1.getSelectedItem();
        String cat=(String)c2.getSelectedItem();
        
        System.out.println(typ);
        String name="",column="";
        if(typ.equals("Physical Book"))
        {name="physicalbooks";
        b4.setVisible(true);
        }
        else if(typ.equals("Digital book"))
        {
            name="digitalbooks";
            b3.setVisible(true);
            b4.setVisible(false);
        }
        if(cat.equals("Name"))
            {
                column="bookname";
            }
        else if(cat.equals("Author"))
            {
                column="author";
            }
           else if(cat.equals("Category"))
            {
                column="category";
            }
        
         DefaultListModel<String> dm = new DefaultListModel<String>();
         try{  
                                        Class.forName("oracle.jdbc.driver.OracleDriver");  
                                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","library","amit");   
                                        Statement stmt=con.createStatement(); 
                                        
                                      
                                        ResultSet rs= stmt.executeQuery("select bookname from "+name+" where "+column+" like '%"+tf1.getText()+"%'");
                                        
                                        while(rs.next())
                                        {
                                            
                                            String str=rs.getString(1);
                                            dm.addElement(str);
                                            rs.next();
                                        }
                                        
                                        
                                        
                                        con.close();  
                                         
  
                                      }catch(Exception e){ System.out.println(e);}
        
        ls.setModel(dm);



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    int click=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String sp=ls.getSelectedValue();
String typ=(String)c1.getSelectedItem();
        String cat=(String)c2.getSelectedItem();
        System.out.println(typ);
        String name="",column="";
        if(typ.equals("Physical Book"))
        {name="physicalbooks";
        }
        else if(typ.equals("Digital book"))
        {
            name="digitalbooks";
        }
        if(cat.equals("Name"))
            {
                column="bookname";
            }
        else if(cat.equals("Author"))
            {
                column="author";
            }
           else if(cat.equals("Category"))
            {
                column="category";
            }

try{  
                                        Class.forName("oracle.jdbc.driver.OracleDriver");  
                                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","library","amit");   
                                        Statement stmt=con.createStatement(); 
                                        
                                      
                                        ResultSet rs= stmt.executeQuery("select * from "+name+" where bookname='"+sp+"'");
                                        
                                        rs.next();
                                        String bookid,bookname,author,desc,loc,cato,avai;
                                        l9.setText(rs.getString(1));
                                        l10.setText(rs.getString(2));
                                        l11.setText(rs.getString(3));
                                        ta2.append(rs.getString(4));
                                       l14.setText(rs.getString(5));
                                       l12.setText(rs.getString(6));
                                        l13.setText(rs.getString(7));
                                        if(rs.getString(7).equals("available"))
                                                {
                                                    l13.setForeground(Color.green);
                                                }//***/
                                        else
                                        {
                                            l13.setForeground(Color.red);
                                            b4.setVisible(false);
                                        }
                                        
                                        
                                        con.close();  
                                         
  
                                      }catch(Exception e){ System.out.println(e);}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String sp=ls.getSelectedValue();
String typ=(String)c1.getSelectedItem();
        String cat=(String)c2.getSelectedItem();
        System.out.println(typ);
        String name="",column="";
        if(typ.equals("Physical Book"))
        {name="physicalbooks";
        }
        else if(typ.equals("Digital book"))
        {
            name="digitalbooks";
        }
        if(cat.equals("Name"))
            {
                column="bookname";
            }
        else if(cat.equals("Author"))
            {
                column="author";
            }
           else if(cat.equals("Category"))
            {
                column="category";
            }

try{  
                                        Class.forName("oracle.jdbc.driver.OracleDriver");  
                                        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","library","amit");   
                                        Statement stmt=con.createStatement(); 
                                        
                                      
                                        ResultSet rs= stmt.executeQuery("select url from "+name+" where bookname='"+sp+"'");
                                        
                                        rs.next();
                                        
                                        String url=rs.getString(1);
                                        download d1= new download();
                                        d1.down(sp, url);
                                        open o=new open(sp);                                       
                                        
                                        
                                        
                                        con.close();  
                                         
  
                                      }catch(Exception e){ System.out.println(e);}
// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
if(click<2)
{click++;
l13.setText("not Available") ;
l13.setForeground(Color.red);
JOptionPane.showMessageDialog(null,"Your book is booked");
}
else
{
JOptionPane.showMessageDialog(null,"Sorry you can maximum take 2 books at a time");
}// TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
frame1 f1= new frame1();
f1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booksearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booksearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booksearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booksearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booksearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l9;
    private javax.swing.JList<String> ls;
    private javax.swing.JTextArea ta2;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
